site_name: My Docs
theme:
  name: 'material'
  feature:
    tabs: true

nav:
  - Overview: 
    - SWNetwork SDK: index.md
    - Installation: installation.md
  - Tutorials:
    - Top-Down Shooter:
      - Introduction: tutorials/top-down/introduction.md
      - Installation: tutorials/top-down/installation.md
      - Setting up the NetworkClient: tutorials/top-down/set-up-the-networkclient.md
      - Sync Player Transform: tutorials/top-down/sync-player-transform.md
      - Setting up the SceneSpawner: tutorials/top-down/set-up-the-scenespawner.md
      - Test and Play: tutorials/top-down/test-and-play.md
      - Remote Events: tutorials/top-down/remote-events.md
      - SyncProperties: tutorials/top-down/sync-properties.md
      - Player Respawn: tutorials/top-down/player-respawn.md
      - Updating Room States: tutorials/top-down/update-room-states.md
      - Winning the Game: tutorials/top-down/win-game.md
  - SDK:
    - NetworkClient:
      - Overview: sdk/networkclient/overview.md
      - Configuration: sdk/networkclient/configuration.md
      - Check-in: sdk/networkclient/checkin.md
      - Game Servers: sdk/networkclient/gameservers.md
      - Network Status Events: sdk/networkclient/networkstatusevent.md
    - Gameplay:
      - Overview: sdk/gameplay/overview.md
      - NetworkID: sdk/gameplay/networkid.md
      - RealtimeAgent: sdk/gameplay/realtimeagent.md
  - API Reference:
    - NetworkClient:
      - Classes:
        - NetworkClient:
          - Summary: reference/networkclient/classes/networkclient/summary.md
          - Methods:
            - CheckIn(): reference/networkclient/classes/networkclient/checkin.md
            - ConnectToRoom(Action<bool>): reference/networkclient/classes/networkclient/connecttoroom.md
            - DisconnectFromRoom(): reference/networkclient/classes/networkclient/disconnectfromroom.md
            - FinsSpawner(ushort): reference/networkclient/classes/networkclient/findspawner.md


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde